Write a function so that the columns of the output matrix are powers of the input vector. 
The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 


In [2]:
import numpy as np
from numpy.random import randint as ri

In [3]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
#By vander method
np.vander(a,N=4,increasing=True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

In [5]:
#By own function
def vander_new(ivector,N,Increasing=False):
    if Increasing == False:
        out_matrix = np.matrix([i**(N-j-1) for i in ivector for j in range(N)])
        out_matrix = out_matrix.reshape(ivector.size,N)
    else:
        out_matrix = np.matrix([i**j for i in ivector for j in range(N)])
        out_matrix = out_matrix.reshape(ivector.size,N)
    return out_matrix
        
    

In [6]:
a = np.array([1,2,3,4])
a=vander_new(a,4,Increasing=True)
a

matrix([[ 1,  1,  1,  1],
        [ 1,  2,  4,  8],
        [ 1,  3,  9, 27],
        [ 1,  4, 16, 64]])

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of  the given sequence is defined as follows: 
The moving average sequence has n-k+1 elements as shown below. 
The moving averages with k=4 of a ten-value sequence (n=10) is shown below 
i 1 2 3 4 5 6 7 8 9 10 
===== == == == == == == == == == == 
Input 10 20 30 40 50 60 70 80 90 100  
y1 25 = (10+20+30+40)/4 
y2 35 = (20+30+40+50)/4 
y3 45 = (30+40+50+60)/4 
y4 55 = (40+50+60+70)/4 
y5 65 = (50+60+70+80)/4 
y6 75 = (60+70+80+90)/4 
y7 85 = (70+80+90+100)/4 
Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question: Write a function to find moving average in an array over a window:  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 


In [19]:
def moving_average(a, K=3) :
    final_list = []
    i =0
    while i < len(a) -K+1:
        the_list = a[i:i+K]
        total = sum(the_list)/K
        i = i+1
        final_list.append(total)
    return np.array(final_list,dtype=int)
        
           
    
    
          


In [20]:
input1 = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
output = moving_average(input1,3)
output

array([  5,   4,   5,   6,   9,  28,  49,  72,  84,  93, 116])